up/urls.py
import os.path
from django.conf import settings
from django.conf.urls import *

from marking.views import *
from django.views.generic.simple import direct_to_template
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
  

## Page ## 
	(r'^$', main_page),
	(r'^user/(\w+)/$', user_page),
	(r'^bookmark_of/(\w+)/$', bookmark_of),
	(r'tag/([^\s]+)/$', tag_page),
	(r'tag/$', tag_cloud_page),
	(r'^search/$', search_page),
	(r'^search_index/$',search_indexpage),
  	(r'^hot/$', popular_page),
 	(r'^profile/(\w+)/$', userprofile),
 	(r'^edit/(\w+)/$', edit_userprofile),
  	(r'^bookmark/(\d+)/$', bookmark_page),
  	(r'^following_list/(\w+)/$', following),
	(r'^follower_list/(\w+)/$', follower),
	(r'^mycomment/(\d+)/$', mycomment),
	(r'^rank/$', rank),
	(r'^rank/add/$', friend_add_rank),
	(r'^test/$', test),
	#(r'^accounts/profile/$', re_aflogin),
	(r'^comments/posted/$', redirect_comment),
	
## Friend ##	
  	(r'^friends/(\w+)/$', friends_page),
  	(r'^friend/add/$', friend_add),
  	(r'^friend/delete/$', friend_delete),
## Session ##
  	(r'^login/$', 'django.contrib.auth.views.login'), #'django.contrib.auth.views.login'
  	(r'^logout/$', logout_page),
  	
  	(r'^register/$', register_page),
  	(r'^register/success/$',register_success),
## Content ##
  	(r'^save/$', bookmark_save_page),
	(r'^delete/$', bookmark_delete),
  	(r'^vote/$', bookmark_vote_page),
  	(r'^comments/', include('django.contrib.comments.urls')),
## Ajax ##
	(r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),
  
## Friends ##  
	(r'^friends/(\w+)/$', friends_page),
  	(r'^friend/add/$', friend_add),
## Admin ##
  	(r'^admin/', include(admin.site.urls)),

## ForTesting ##
	(r'^test_clearbookmark/(\w+)/$', test_clearbookmark),
	(r'^test_checkregister/(\w+)/$', test_checkregister),
	(r'^test_searching/$', test_searching),
	(r'^test_nosearching/$', test_nosearching),
	(r'^test_adding/$', test_adding),
	(r'^test_edit/$', test_edit),
	(r'^test_delete/$', test_delete),
	(r'^test_vote/$', test_vote),
	(r'^test_isfriend/(\w+)/$', test_isfriend),
	(r'^test_comment/(\w+)/$', test_comment),
	(r'^test_isvoted/(\w+)/$', test_isvoted),
	(r'^test_privacy/$', test_privacy),
)

#urlpatterns += patterns('django.views.generic.sample',
#&nbsp (r'^/login/$' , 'direct_to_template',{'template':'base_login.html'}),)


###  MEDIA ###
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_DOC_ROOT}),    
)

comments/models.py
from django.db import models

from django.contrib.comments.models import Comment
from mptt.models import MPTTModel, TreeForeignKey

class MPTTComment(MPTTModel, Comment):
    """ Threaded comments - Add support for the parent comment store and MPTT traversal"""
    # a link to comment that is being replied, if one exists
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    class MPTTMeta:
        # comments on one level will be ordered by date of creation
        order_insertion_by=['submit_date']

    class Meta:
        ordering=['tree_id','lft']

marking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template import Context
from django.db.models.signals import post_save
from django.conf import settings
from django.template.loader import get_template
from django import forms

from mptt.models import MPTTModel, TreeForeignKey

from django.contrib import admin
##
class Link(models.Model):
	url = models.URLField(unique=True)

	def __str__(self):
		return self.url
	class Admin:
		pass

################
class User(models.Model):
	username = models.ForeignKey(User)
	first_name = models.CharField(max_length=30)
	last_name =  models.CharField(max_length=30)
	email =  models.EmailField()
	password =  forms.CharField(widget=forms.PasswordInput)
    from_friend = models.ForeignKey(User, related_name='friend_set')
	to_friend = models.ForeignKey(User, related_name='to_friend_set')
  
	def __str__(self):
		return '%s, %s,%s ' % (username ,self.from_friend.username, self.to_friend.username)
################
class Bookmark(models.Model):
	
	title = models.CharField(max_length=200)
	user = models.ForeignKey(User)
	link = models.ForeignKey(Link)
	date_add = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField()
	shared_state = models.BooleanField()
	def __str__(self):
		return '%s, %s' % (self.user.username, self.link.url)
		
	def get_absolute_url(self):
		return self.link.url 
		
	class Admin:
		list_display = ('title', 'link','user')
		list_filter = ('user', )
		ordering = ('title', )
		search_fields = ('title', )
	
##
class Tag(models.Model):
	name = models.CharField(max_length=64, unique=True)
	bookmarks = models.ManyToManyField(Bookmark)

	def __str__(self):
		return self.name
	class Admin:
		pass
##
class SharedBookmark(models.Model):
	bookmark = models.ForeignKey(Bookmark, unique=True)
	date = models.DateTimeField(auto_now_add=True)
	votes = models.IntegerField(default=1)
	users_voted = models.ManyToManyField(User)
	status = models.BooleanField()
	#owner_id = models.IntegerField()
	

	def __str__(self):
		return '%s, %s' % self.bookmark, self.votes
    
	class Admin:
		pass
		

#############################


class Post(models.Model):
	
	text = models.TextField()
	added  = models.DateTimeField(auto_now_add=True)

comments/forms.py
from django import forms
from django.contrib.admin import widgets        
from django.contrib.comments.forms import CommentForm                            
from models import MPTTComment

class MPTTCommentForm(CommentForm):
    parent = forms.ModelChoiceField(queryset=MPTTComment.objects.all(), required=False, widget=forms.HiddenInput)

    def get_comment_model(self):
        # Use our custom comment model instead of the built-in one.
        return MPTTComment

    def get_comment_create_data(self):
        # Use the data of the superclass, and add in the parent field field
        data = super(MPTTCommentForm, self).get_comment_create_data()
        data['parent'] = self.cleaned_data['parent']
        return data

templates/comments/form.html
{% if user.is_authenticated %}
  <form action="/comments/post/" method="post">{% csrf_token %}

	{{ form.content_type }}
	{{ form.object_pk }}
	{{ form.timestamp }}
	{{ form.security_hash }}
    <p><label>Post a comment:</label><br />
    <textarea name="comment" rows="10" cols="60"></textarea></p>
    <input type="hidden" name="options" value="{{ options }}" />
    <input type="hidden" name="target" value="{{ target }}" />
    <input type="hidden" name="gonzo" value="{{ hash }}" />
    <input type="hidden" name="reid" value="TEST REDIRECTION" />
    <input type="submit" name="post" value="submit comment" />
  </form>
{% else %}
  <p>Please <a href="/login/">log in</a> to post comments.</p>
{% endif %}	

templates/comments/posted.html
{% extends "base_login.html" %}

{% block title %}Comment Posted Successfully{% endblock %}
{% block head %}Comment Posted Successfully{% endblock %}

{% block content %}


  <br><br><center><p>Leave Comment Sucessfull. Click view to view your comment</p>
  <p><a href="/bookmark/{{ query }}">View</a></center>

  
{% endblock %}

{% block popula %}
{% if people %}
	{% for to_friend in people %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/profile/{{ to_friend }}" target="_blank"><font color="#39b54a">&nbsp;<b>{{ to_friend }}</b></font></a><br>
	{% endfor %}
{% endif %}
{% endblock %}
{% block pic1 %}myurl.png{% endblock %}
{% block pic2 %}mynw.png{% endblock %}
{% block pic3 %}hoturl.png{% endblock %}
{% block pic4 %}groupac.png{% endblock %}

{% block yourtag %}
{% if allbookmark %}
	{% for bookmark in allbookmark %}
		{% if bookmark.tag_set.all %}  
               
			{% for tag in bookmark.tag_set.all %}
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{{ MEDIA_URL }}images/starlogo.png" width="15" height="15" border="0">&nbsp;<a href="/tag/{{ tag.name|urlencode }}" id="upname2"><font color="#39b54a">&nbsp;<b>{{ tag.name|escape }}</b></font></b></font></a><br>			
			{% endfor %}
		{% endif %}
	{% endfor %}
{% else %}
    		<br /><center>No Tag.</center><br />
{% endif %}
{% endblock %}

templates/comments/preview.html
{% extends "base_view_comment.html" %}
{% load i18n %}

{% block title %}{% trans "Preview your comment" %}{% endblock %}

{% block content %}
  {% load comments %}
  <tabel width="100%" border="0" cellspacing="0" celpadding="0">
	<tr>
	<td width="300">&nbsp;</td>
	<td align="left" valign="top">
		<form action="{% comment_form_target %}" method="post">{% csrf_token %}
		    {% if next %}<div><input type="hidden" name="next" value="{{ next }}" /></div>{% endif %}
		    {% if form.errors %}
		    <h1>{% blocktrans count counter=form.errors|length %}<img src="{{ MEDIA_URL }}/images/commentballoon.gif" width="18" height="18" alt="Comment" /> Comment can't empty.{% plural %}Comment can't be empty.{% endblocktrans %}</h1>
		    {% else %}
		    <h1><img src="{{ MEDIA_URL }}/images/commentballoon.gif" width="18" height="18" alt="Up" /> {% trans "Preview your comment" %}</h1>
		      Your Comment is :<table><tr bgcolor="red">
			<blockquote>{{ comment|linebreaks }}</blockquote>
			</tr></table>
		      <p>
		      
		      </p>
		    {% endif %}
		    {% for field in form %}
		      {% if field.is_hidden %}
			<div>{{ field }}</div>
		      {% else %}
			{% if field.errors %}{{ field.errors }}{% endif %}
			<p
			  {% if field.errors %} class="error"{% endif %}
			  {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
				  {% if field.label == "Comment" %}
					{{ field }}
				  {% else %}
					
				  {% endif %}
			</p>
		      {% endif %}
		    {% endfor %}
		    <p class="submit">
		    <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
		    <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}" />
		    </p>
		  </form>
	</td>
	<td width="300">&nbsp;</td>
	</tr>
  </table>
{% endblock %}


{% block pic1 %}myurl.png{% endblock %}
{% block pic2 %}mynw.png{% endblock %}
{% block pic3 %}hoturl.png{% endblock %}
{% block pic4 %}groupac.png{% endblock %}